EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/ViewModels/Tickets/TicketsIndexViewModel.cs
using EpamLabs.TicketResale.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EpamLabs.TicketResale.Presentation.ViewModels.Tickets
{
    public class TicketsIndexViewModel
    {
        public IEnumerable<Ticket> ForSale { get; set; }
        public IEnumerable<Order> Ordered { get; set; }
        public IEnumerable<Order> Sold { get; set; }
        public TicketsIndexMessage Message { get; set; }
    }

    public enum TicketsIndexMessage
    {
        None,
        TicketAdded,
        TicketRemoved,
        TicketSaleConfirmed,
        TicketSaleRejected,
        Error
    }

    public static class IndexMessageExtensions
    {
        public static string GetMessage(this TicketsIndexMessage message)
        {
            switch (message)
            {
                case TicketsIndexMessage.TicketAdded:
                    return "Ticket added to your list for sale";
                case TicketsIndexMessage.TicketRemoved:
                    return "Ticket removed from your list for sale";
                case TicketsIndexMessage.TicketSaleConfirmed:
                    return "Ticket sale confirmed";
                case TicketsIndexMessage.TicketSaleRejected:
                    return "Ticket sale rejected";
                case TicketsIndexMessage.Error:
                    return "Error occured. Please try again.";
                default:
                    return string.Empty;
            }
        }
    }
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Controllers/OrdersController.cs
using EpamLabs.TicketResale.Business;
using EpamLabs.TicketResale.Business.Infrastructure;
using EpamLabs.TicketResale.Data;
using EpamLabs.TicketResale.Presentation.ViewModels.Orders;
using EpamLabs.TicketResale.Presentation.ViewModels.Tickets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace EpamLabs.TicketResale.Presentation.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly ILogger<OrdersController> _logger;
        private readonly ITicketService _tickets;
        private readonly IUserService _users;
        private readonly IEventService _events;
        private readonly IOrderService _orders;

        public OrdersController(
            ILoggerFactory loggerFactory,
            ITicketService tickets,
            IUserService users,
            IEventService events,
            IOrderService orders)
        {
            _logger = loggerFactory.CreateLogger<OrdersController>();
            _tickets = tickets;
            _users = users;
            _events = events;
            _orders = orders;
        }

        public IActionResult Index(OrdersIndexMessage message = OrdersIndexMessage.None)
        {
            return View(new OrdersIndexViewModel
            {
                Message = message,
                Orders = _orders.GetForBuyer(_users.GetCurrent())
            });
        }
        
        public IActionResult Create(int id, string returnUrl = null)
        {
            var ticket = _tickets.GetById(id);
            if (ticket == null)
            {
                _logger.LogWarning($"Failed to find ticket with Id: {id}.");
                return NotFound();
            }
            ViewBag.ReturnUrl = returnUrl;
            return View(ticket);
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult CreateConfirmed(int id)
        {
            try
            {
                var user = _users.GetCurrent();
                _orders.PlaceOrder(user, id);
                return RedirectToAction(nameof(Index), new { message = OrdersIndexMessage.OrderPlaced });
            }
            catch (UnauthorizedException)
            {
                return StatusCode(409);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }
        
        public IActionResult Cancel(int id)
        {
            var order = _orders.GetById(id);
            if (order == null)
            {
                return NotFound();
            }
            var user = _users.GetCurrent();
            if (user == null || order.User.Id != _users.GetCurrent().Id)
            {
                return StatusCode(409);
            }
            return View(order);
        }

        [HttpPost, ActionName("Cancel")]
        [ValidateAntiForgeryToken]
        public IActionResult CancelConfirmed(int id)
        {
            try
            {
                var user = _users.GetCurrent();
                _orders.CancelOrder(user, id);
                _logger.LogInformation("Order cancelled.");
                return RedirectToAction(nameof(Index), new { message = OrdersIndexMessage.OrderCancelled });
            }
            catch (UnauthorizedException)
            {
                return StatusCode(409);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        public IActionResult Confirm(int id)
        {
            var order = _orders.GetById(id);
            if (order == null)
            {
                return NotFound();
            }
            var user = _users.GetCurrent();
            if (order.Ticket.UserId != user.Id)
            {
                return new StatusCodeResult(409);
            }
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Confirm(Order model)
        {
            var order = _orders.GetById(model.Id);
            if (order == null)
            {
                return NotFound();
            }
            var user = _users.GetCurrent();
            if (order.Ticket.UserId != user.Id)
            {
                _logger.LogWarning("Unauthorized attempt to confirm an order.");
                return StatusCode(409);
            }
            order.TrackingNumber = model.TrackingNumber;
            try
            {
                _orders.ConfirmOrder(user, order);
                _logger.LogInformation("Order confirmed successfully.");
                return RedirectToAction("Index", "Tickets", new { message = TicketsIndexMessage.TicketSaleConfirmed });
            }
            catch (UnauthorizedException)
            {
                return StatusCode(409);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        public IActionResult Reject(int id)
        {
            var order = _orders.GetById(id);
            if (order == null)
            {
                return NotFound();
            }
            var user = _users.GetCurrent();
            if (order.Ticket.UserId != user.Id)
            {
                return StatusCode(409);
            }
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Reject(Order model)
        {
            var order = _orders.GetById(model.Id);
            if (order == null)
            {
                return NotFound();
            }
            var user = _users.GetCurrent();
            if (order.Ticket.UserId != user.Id)
            {
                _logger.LogWarning("Unauthorized attempt to reject an order.");
                return StatusCode(409);
            }
            order.RejectReason = model.RejectReason;
            try
            {
                _orders.RejectOrder(user, order);
                _logger.LogInformation("Order rejected successfully.");
                return RedirectToAction("Index", "Tickets", new { message = TicketsIndexMessage.TicketSaleRejected });
            }
            catch (UnauthorizedException)
            {
                return StatusCode(409);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

    }
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Controllers/TicketsController.cs
using EpamLabs.TicketResale.Business;
using EpamLabs.TicketResale.Data;
using EpamLabs.TicketResale.Presentation.ViewModels.Tickets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace EpamLabs.TicketResale.Presentation.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly ILogger<TicketsController> _logger;
        private readonly ITicketService _tickets;
        private readonly IOrderService _orders;
        private readonly IUserService _users;
        private readonly IEventService _events;

        public TicketsController(
            ILoggerFactory loggerFactory,
            ITicketService tickets,
            IOrderService orders,
            IUserService users,
            IEventService events)
        {
            _logger = loggerFactory.CreateLogger<TicketsController>();
            _tickets = tickets;
            _orders = orders;
            _users = users;
            _events = events;
        }

        public IActionResult Index(TicketsIndexMessage message = TicketsIndexMessage.None)
        {
            var user = _users.GetCurrent();
            var model = new TicketsIndexViewModel
            {
                ForSale = _tickets.GetForUser(user, TicketState.ForSale),
                Ordered = _orders.GetForSeller(user, OrderState.Pending),
                Sold = _orders.GetForSeller(user, OrderState.Confirmed),
                Message = message
            };
            return View(model);
        }
        
        public IActionResult Create(int? eventId)
        {
            ViewBag.Events = _events.GetAllAsSelectList();
            return View(new Ticket
            {
                EventId = eventId ?? 0,
                UserId = _users.GetCurrent().Id,
                State = TicketState.ForSale
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Ticket model)
        {
            if (ModelState.IsValid)
            {
                if (model.UserId != _users.GetCurrent().Id
                    || model.State != TicketState.ForSale)
                {
                    return NotFound();
                }
                _tickets.Create(model);
                _logger.LogInformation("A new ticket added.");
                return RedirectToAction(nameof(Index), new { message = TicketsIndexMessage.TicketAdded });
            }
            ViewBag.Events = _events.GetAllAsSelectList();
            return View(model);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ticket = _tickets.GetById((int)id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewBag.Events = _events.GetAllAsSelectList();
            return View(ticket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (ticket.UserId != _users.GetCurrent().Id)
                {
                    return NotFound();
                }
                _tickets.Update(ticket);
                _logger.LogInformation("A ticket was updated.");
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Events = _events.GetAllAsSelectList();
            return View(ticket);
        }

        public IActionResult Delete(int id)
        {
            var ticket = _tickets.GetById(id);
            ticket.Event = _events.GetById(ticket.EventId);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (_tickets.IsSafeToDelete(id))
            {
                var ticket = _tickets.GetById(id);
                if (ticket == null 
                    || ticket.UserId != _users.GetCurrent().Id)
                {
                    return NotFound();
                }
                _tickets.Delete(ticket);
            }
            else
            {
                _logger.LogWarning("Deleting ticket failed.");
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Tickets/Create.cshtml
@model Ticket

@{
    ViewData["Title"] = "Add ticket";
}

<div class="">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_UserSidebar")
        </div>
        <div class="col-md-10">
            <h2 asp-loc>Add ticket for sale</h2>
            <hr />
            <form asp-action="Create" asp-antiforgery="true">
                <div class="form-horizontal">
                    <div asp-validation-summary="All" class="text-danger" asp-loc></div>
                    <input asp-for="UserId" type="hidden" />
                    <input asp-for="State" type="hidden" />
                    <div class="form-group">
                        <label asp-for="Event" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <select asp-for="EventId" asp-items="ViewBag.Events" class="form-control"></select>
                            <span asp-validation-for="EventId" class="text-danger" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Comment" class="col-md-2 control-label" asp-loc>Comment</label>
                        <div class="col-md-10">
                            <input asp-for="Comment" class="form-control" />
                            <span asp-validation-for="Comment" class="text-danger" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-default" asp-loc>Add</button>
                        </div>
                    </div>
                </div>
            </form>

            <div>
                <a asp-action="Index" asp-loc>Back to my tickets</a>
            </div>

        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Tickets/Delete.cshtml
@model Ticket

@{
    ViewData["Title"] = "Delete ticket";
}

<div class="">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_UserSidebar")
        </div>
        <div class="col-md-10">
            <h2 asp-loc>Delete ticket</h2>

            <h3 asp-loc>Are you sure you want to delete this ticket?</h3>
            <div>
                <div>
                    @await Html.PartialAsync("_MyTicketPartial", Model)
                </div>

                <form asp-action="Delete">
                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        <a asp-action="Index" asp-loc>Back to List</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Tickets/Edit.cshtml
@model Ticket

@{
    ViewData["Title"] = "Edit ticket";
}

<div class="">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_UserSidebar")
        </div>
        <div class="col-md-9">
            <h2 asp-loc>Edit ticket</h2>
            <hr />
            <form asp-action="Edit" asp-antiforgery="true">
                <div class="form-horizontal">
                    <div asp-validation-summary="All" class="text-danger" asp-loc></div>
                    <input asp-for="EventId" type="hidden" />
                    <input asp-for="UserId" type="hidden" />
                    <div class="form-group">
                        <label asp-for="Event" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            @await Html.PartialAsync("_EventPartial", Model.Event)
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Comment" class="col-md-2 control-label" asp-loc>Comment</label>
                        <div class="col-md-10">
                            <input asp-for="Comment" class="form-control" />
                            <span asp-validation-for="Comment" class="text-danger" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-default" asp-loc>Save</button> |
                            <a asp-action="Index" asp-loc>Back to List</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Tickets/Index.cshtml
@using EpamLabs.TicketResale.Presentation.ViewModels.Tickets
@model TicketsIndexViewModel
@{
    ViewData["Title"] = "Tickets";
}

<div class="">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_UserSidebar")
        </div>
        <div class="col-md-10">
            <div>
                @if (Model.Message != TicketsIndexMessage.None)
                {
                    <div class="alert alert-success" asp-loc>
                        @Model.Message.GetMessage()
                    </div>
                }

                <h2 asp-loc>My tickets</h2>

                <p><a asp-action="Create" asp-loc>Add ticket</a></p>
                @if (Model.ForSale?.Count() > 0 ||
                        Model.Ordered?.Count() > 0 ||
                        Model.Sold?.Count() > 0)
                {
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#forSale" asp-loc>For sale</a></li>
                        <li>
                            <a data-toggle="tab" href="#ordered" asp-loc>
                                Pending
                                @if (Model.Ordered?.Count() > 0)
                {
                                    <span class="badge">@Model.Ordered.Count()</span>
                                }
                            </a>
                        </li>
                        <li><a data-toggle="tab" href="#sold" asp-loc>Sold</a></li>
                    </ul>

                    <div class="tab-content">
                        <div id="forSale" class="tab-pane fade in active">
                            @if (Model.ForSale?.Count() > 0)
                {
                    foreach (var item in Model.ForSale)
                    {
                                    <div class="edit-item-container">
                                        @await Html.PartialAsync("_MyTicketPartial", item)
                                        <div class="edit-delete-group">
                                            <a asp-action="Edit" asp-route-id="@item.Id" title="Edit">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a> |
                                            <a asp-action="Delete" asp-route-id="@item.Id" title="Remove">
                                                <span class="glyphicon glyphicon-remove"></span>
                                            </a>
                                        </div>
                                    </div>
                                }
                            }
                            else
                            {
                                <p asp-loc>Your list of tickets for sale is empty.</p>
                            }
                        </div>
                        <div id="ordered" class="tab-pane fade">
                            @if (Model.Ordered?.Count() > 0)
                {
                    foreach (var item in Model.Ordered)
                    {
                                    <div class="edit-item-container">
                                        @await Html.PartialAsync("_MyTicketPartial", item.Ticket)
                                        <p>
                                            <strong asp-loc>Buyer: </strong>@item.User.FirstName @item.User.LastName
                                            <div>
                                                <a asp-action="Confirm" asp-controller="Orders" asp-route-id="@item.Id" class="btn btn-primary" asp-loc>Confirm</a>
                                                <a asp-action="Reject" asp-controller="Orders" asp-route-id="@item.Id" class="btn btn-default" asp-loc>Reject</a>
                                            </div>
                                        </p>
                                    </div>
                                }
                            }
                            else
                            {
                                <p asp-loc>There's no orders to confirm.</p>
                            }
                        </div>
                        <div id="sold" class="tab-pane fade">
                            @if (Model.Sold?.Count() > 0)
                {
                    foreach (var item in Model.Sold)
                    {
                                    <div class="edit-item-container">
                                        @await Html.PartialAsync("_MyTicketPartial", item.Ticket)
                                        <p><strong asp-loc>Buyer: </strong> @item.User.FirstName @item.User.LastName</p>
                                        <p><strong asp-loc>Tracking No.: </strong> @item.TrackingNumber</p>
                                    </div>
                                }
                            }
                            else
                            {
                                <p asp-loc>Your list of sold tickets is empty.</p>
                            }
                        </div>
                    </div>
                }
                else
                {
                    <p asp-loc>Your list of tickets is empty.</p>
                }
            </div>
        </div>
    </div>
</div>





            