EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Controllers/CitiesController.cs
using EpamLabs.TicketResale.Business;
using EpamLabs.TicketResale.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace EpamLabs.TicketResale.Presentation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        private readonly ILogger _logger;
        private readonly ICityService _cities;

        public CitiesController(
            ILoggerFactory loggerFactory,
            ICityService cities)
        {
            _logger = loggerFactory.CreateLogger<CitiesController>();
            _cities = cities;
        }

        public IActionResult Index()
        {
            return View(_cities.GetAll().OrderBy(x => x.Name));
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(City model)
        {
            if (ModelState.IsValid)
            {
                _cities.Create(model);
                _logger.LogInformation("A new city created.");
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var city = _cities.GetById((int)id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, City model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _cities.Update(model);
                _logger.LogInformation("A city was updated.");
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = _cities.GetById((int)id);
            if (city == null)
            {
                return NotFound();
            }

            if (!_cities.IsSafeToDelete((int)id))
            {
                ViewBag.Deleteable = false;
            }
            else
            {
                ViewBag.Deleteable = true;
            }
            return View(city);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_cities.IsSafeToDelete(id))
            {
                var city = _cities.GetById(id);
                _cities.Delete(city);
            }
            return RedirectToAction("Index");
        }
    }
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Controllers/EventsController.cs
using EpamLabs.TicketResale.Business;
using EpamLabs.TicketResale.Data;
using EpamLabs.TicketResale.Presentation.ViewModels.Events;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace EpamLabs.TicketResale.Presentation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EventsController : Controller
    {
        private const string IMAGES_SUBFOLDER = "images";

        private readonly IEventService _events;
        private readonly ITicketService _tickets;
        private readonly IVenueService _venues;
        private readonly IUserService _users;
        private readonly FileService _fileService;
        private readonly ILogger _logger;
        private readonly IHostingEnvironment _env;

        public EventsController(
            IEventService events,
            ITicketService tickets,
            IVenueService venues,
            IUserService users,
            ILoggerFactory loggerFactory,
            FileService fileService,
            IHostingEnvironment env)
        {
            _events = events;
            _tickets = tickets;
            _venues = venues;
            _users = users;
            _fileService = fileService;
            _logger = loggerFactory.CreateLogger<EventsController>();
            _env = env;
        }

        public IActionResult Index()
        {
            return View(_events.GetAll());
        }

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();
            var model = new EventDetailsViewModel();
            model.Event = _events.GetById((int)id);
            if (model.Event == null)
            {
                _logger.LogWarning($"Event with id={id} not found.");
                return NotFound();
            }
            model.TicketsForSale = _tickets.GetForSale(model.Event, _users.GetCurrent());
            return View(model);
        }

        public IActionResult Create()
        {
            ViewBag.Venues = _venues.GetAllAsSelectList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Event model, IFormFile image = null)
        {
            if (ModelState.IsValid)
            {
                model.Image = _events.UploadImage(image, _env.WebRootPath, IMAGES_SUBFOLDER);
                _events.Create(model);
                _logger.LogInformation("A new event created.");
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Venues = _venues.GetAllAsSelectList();
            return View(model);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var @event = _events.GetById((int)id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewBag.Venues = _venues.GetAllAsSelectList();
            return View(@event);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Event model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _events.Update(model);
                _logger.LogInformation("An event was updated.");
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Venues = _venues.GetAllAsSelectList();
            return View(model);
        }

        [HttpPost]
        public IActionResult UpdateImage(int id, IFormFile image = null)
        {
            var @event = _events.UpdateImage(id, image, _env.WebRootPath, IMAGES_SUBFOLDER);
            return RedirectToAction(nameof(Edit), new { id = id });
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = _events.GetById((int)id);
            if (@event == null)
            {
                return NotFound();
            }
            if (!_events.IsSafeToDelete((int)id))
            {
                ViewBag.Deleteable = false;
            }
            else
            {
                ViewBag.Deleteable = true;
            }
            return View(@event);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_events.IsSafeToDelete(id))
            {
                var @event = _events.GetById(id);
                _fileService.RemoveFile(_env.WebRootPath, @event.Image);
                _events.Delete(@event);
            }
            return RedirectToAction("Index");
        }

        #region Helpers
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(EventsController.Index),
                nameof(EventsController).Replace("Controller", ""));
            }
        }

        #endregion
    }
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Controllers/UsersController.cs
using EpamLabs.TicketResale.Business;
using EpamLabs.TicketResale.Data;
using EpamLabs.TicketResale.Presentation.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;

namespace EpamLabs.TicketResale.Presentation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserService _users;
        private readonly ILogger<UsersController> _logger;

        public UsersController(
            UserManager<ApplicationUser> userManager,
            IUserService users, 
            ILogger<UsersController> logger)
        {
            _userManager = userManager;
            _users = users;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var current = _users.GetCurrent();
            var model = _users.GetAll()
                .Where(x => x.Id != current.Id)
                .Select(x => new UsersViewModel
                {
                    User = x,
                    RoleName = _userManager.GetRolesAsync(x).Result.FirstOrDefault() ?? "User"
                })
                .AsEnumerable()
                .OrderBy(x => x.User.UserName);
            return View(model);
        }

        public IActionResult GrantAdmin(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = _users.GetById(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(new UsersViewModel
            {
                User = user,
                RoleName = _userManager.GetRolesAsync(user).Result.FirstOrDefault() ?? "User"
            });
        }

        [HttpPost, ActionName("GrantAdmin")]
        [ValidateAntiForgeryToken]
        public IActionResult GrantAdminConfirmed(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = _userManager.FindByIdAsync(id).Result;
            if (user == null)
            {
                return NotFound();
            }
            var result = _userManager.AddToRoleAsync(user, Roles.Admin).Result;
            if (result.Succeeded)
            {
                _logger.LogInformation($"User {user.UserName} has been granted admin rights.");
            }
            else
            {
                _logger.LogInformation($"Unable to grant admin rights to user: {user.UserName}.");
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RevokeAdmin(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = _users.GetById(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(new UsersViewModel
            {
                User = user,
                RoleName = _userManager.GetRolesAsync(user).Result.FirstOrDefault() ?? "User"
            });
        }

        [HttpPost, ActionName("RevokeAdmin")]
        [ValidateAntiForgeryToken]
        public IActionResult RevokeAdminConfirmed(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = _userManager.FindByIdAsync(id).Result;
            if (user == null)
            {
                return NotFound();
            }
            var result = _userManager.RemoveFromRoleAsync(user, Roles.Admin).Result;
            if (result.Succeeded)
            {
                _logger.LogInformation($"Admin rights were revoked for user {user.UserName}.");
            }
            else
            {
                _logger.LogInformation($"Unable to revoke admin rights for user: {user.UserName}.");
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Controllers/VenuesController.cs
using EpamLabs.TicketResale.Business;
using EpamLabs.TicketResale.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;

namespace EpamLabs.TicketResale.Presentation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class VenuesController : Controller
    {
        private readonly ILogger _logger;
        private readonly IVenueService _venues;
        private readonly ICityService _cities;

        public VenuesController(
            ILoggerFactory loggerFactory,
            IVenueService venues,
            ICityService cities)
        {
            _logger = loggerFactory.CreateLogger<VenuesController>();
            _venues = venues;
            _cities = cities;
        }

        public IActionResult Index()
        {
            return View(_venues.GetAll().OrderBy(x => x.Name));
        }

        public IActionResult Create()
        {
            ViewBag.Cities = _cities.GetAllAsSelectList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Venue model)
        {
            if (ModelState.IsValid)
            {
                _venues.Create(model);
                _logger.LogInformation("A new venue created.");
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var venue = _venues.GetById((int)id);
            if (venue == null)
            {
                return NotFound();
            }
            ViewBag.Cities = _cities.GetAllAsSelectList();
            return View(venue);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Venue model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _venues.Update(model);
                _logger.LogInformation("A city was updated.");
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Cities = _cities.GetAllAsSelectList();
            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = _venues.GetById((int)id);
            if (venue == null)
            {
                return NotFound();
            }

            if (!_venues.IsSafeToDelete((int)id))
            {
                ViewBag.Deleteable = false;
            }
            else
            {
                ViewBag.Deleteable = true;
            }
            return View(venue);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_venues.IsSafeToDelete(id))
            {
                var venue = _venues.GetById(id);
                _venues.Delete(venue);
            }
            return RedirectToAction("Index");
        }
    }
}

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Shared/_AdminSidebar.cshtml
<div class="well">
    <p>
        <a asp-controller="Cities" asp-action="Index" asp-loc>Manage cities</a>
        <br />
        <a asp-controller="Venues" asp-action="Index" asp-loc>Manage venues</a>
        <br />
        <a asp-controller="Events" asp-action="Index" asp-loc>Manage events</a>
        <br />
        <a asp-controller="Users" asp-action="Index" asp-loc>Manage users</a>
    </p>
</div>

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Shared/_EventPartial.cshtml
@model Event

<div class="event-content">
    <div class="right">
        <a asp-controller="Events" asp-action="Details" asp-route-id="@Model.Id">
            <img class="center" src="@Model.Image" />
        </a>
    </div>
    <div class="event-description">
        <h3>
            <a asp-controller="Events" asp-action="Details" asp-route-id="@Model.Id">
                @Html.DisplayFor(x => x.Name)
            </a>
        </h3>
        <p class="date">
            @Html.DisplayFor(x => x.Date)
        </p>
        <p>
            @Html.DisplayFor(x => x.Venue.Name), @Html.DisplayFor(x => x.Venue.City.Name)
        </p>
    </div>
</div>

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Shared/_Filter.cshtml
<div class="well">
    <h4 asp-loc>Events filter</h4><br/>
    <form id="filter-form">
        <div class="dropdown example">
            <select id="cities-filter" name="cityIds" multiple class="ui fluid search dropdown">
                <option value="" asp-loc>City</option>
            </select>
        </div>
        <br />
        <br />

        <div class="dropdown example">
            <select id="venues-filter" name="venueIds" multiple class="ui fluid search dropdown">
                <option value="" asp-loc>Venue</option>
            </select>
        </div>
        <br />
        <br />

        <div class="ui form">
            <div class="ui calendar" id="rangestart">
                <div class="ui input left icon">
                    <i class="calendar icon"></i>
                    <input type="text" placeholder="Since" name="since">
                </div>
            </div>
            <div class="ui calendar" id="rangeend">
                <div class="ui input left icon">
                    <i class="calendar icon"></i>
                    <input type="text" placeholder="Until" name="until">
                </div>
            </div>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />

        <div id="filter-name-wrapper" class="ui icon input">
            <input type="text" id="filter-name-input" name="q" placeholder="Event name" class="autocomplete" autocomplete="off"/>
            <i class="search icon"></i>
        </div>
        <br />
        <br />

        <button id="apply-filter" type="button" class="btn btn-primary" asp-loc>Filter</button>
        <button id="reset-filter" type="reset" class="btn btn-default" asp-loc>Reset</button>
    </form>
</div>

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="~/lib/jquery/jquery-ui.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/semantic.css" />
    <link rel="stylesheet" href="~/css/calendar.css" />


    <title asp-loc>@ViewData["Title"] - Ticket Resale</title>
</head>
<body style="margin: auto">
    <div id="header">
        <a id="logo" asp-controller="Home" asp-action="Index" class="">ticket resale</a>
        <div id="user-corner">
            <vc:login />
        </div>
    </div>
    <div id="mynavbar">
        <ul class="left clearfix">
            <li><a asp-controller="Home" asp-action="Index" class="" asp-loc>Home</a></li>
            @if (User.IsInRole(Roles.Admin))
            {
                <li class="dropdown">
                    <a asp-controller="Cities" asp-action="Index" class="dropbtn" asp-loc>Administrator <span class="caret"></span></a>
                    <div class="dropdown-content">
                        <a asp-controller="Cities" asp-action="Index" asp-loc>Manage cities</a>
                        <a asp-controller="Venues" asp-action="Index" asp-loc>Manage venues</a>
                        <a asp-controller="Events" asp-action="Index" asp-loc>Manage events</a>
                        <a asp-controller="Users" asp-action="Index" asp-loc>Manage users</a>
                    </div>
                </li>
            }
        </ul>
        @*<div class="search-and-filter">
            <div class="global-search right clearfix">
                <input class="autocomplete" autocomplete="on" placeholder="Search"/>
                <a href="#"><span class="glyphicon glyphicon-search"></span></a>
            </div>
        </div>*@
    </div>
    
    <div class="body-content main">
        @RenderBody()
        <hr />
    </div>

    <footer id="footer">
        <p asp-loc>&copy; 2016 - Ticket Resale</p>
        <div id="lang-selector" class="col-md-6 text-right">
            <vc:select-language />
        </div>
    </footer>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery/jquery-1.12.4.js"></script>
        <script src="~/lib/jquery/jquery-ui.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/autocomplete.js" asp-append-version="true"></script>
        <script src="~/js/filter.js"></script>
        <script src="~/js/semantic.js"></script>
        <script src="~/js/calendar.js"></script>
        <script src="~/js/dropdown.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/calendar.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Shared/_MyTicketPartial.cshtml
@model Ticket

<div class="event-content">
    <div class="right">
        <a asp-controller="Events" asp-action="Details" asp-route-id="@Model.Event.Id">
            <img class="center" src="@Model.Event.Image" />
        </a>
    </div>
    <div class="event-description">
        <h4 class="price">US $@Html.DisplayFor(x => x.Price) </h4>
        <h3>
            <a asp-controller="Events" asp-action="Details" asp-route-id="@Model.Event.Id">
                @Html.DisplayFor(x => x.Event.Name)
            </a>
        </h3>
        <p class="date tight-line">
            @Html.DisplayFor(x => x.Event.Date)
        </p>
        <p class="tight-line">
            @Html.DisplayFor(x => x.Event.Venue.Name), @Html.DisplayFor(x => x.Event.Venue.City.Name)
        </p>
        <p class="tight-line">
            <em>@Html.DisplayFor(x => x.Comment)</em>
        </p>
    </div>
</div>

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Shared/_OrderPartial.cshtml
@model Order


<div class="event-content">
    <div class="right">
        <a asp-controller="Events" asp-action="Details" asp-route-id="@Model.Id">
            <img class="center" src="@Model.Ticket.Event.Image" />
        </a>
    </div>
    <div class="event-description">
        <h4 class="price">US $@Html.DisplayFor(x => x.Ticket.Price)</h4>
        <h3>
            <a asp-controller="Events" asp-action="Details" asp-route-id="@Model.Id">
                @Html.DisplayFor(x => x.Ticket.Event.Name)
            </a>
        </h3>
        <p class="date tight-line">
            @Html.DisplayFor(x => x.Ticket.Event.Date)
        </p>
        <p class="tight-line">
            @Html.DisplayFor(x => x.Ticket.Event.Venue.Name), @Html.DisplayFor(x => x.Ticket.Event.Venue.City.Name)
        </p>
        <p class="tight-line">
            <em>@Html.DisplayFor(x => x.Ticket.Comment)</em>
        </p>
    </div>
</div>

EpamLabs.TicketResale/EpamLabs.TicketResale.Presentation/Views/Shared/_UserSidebar.cshtml
<div class="well">
    <p>
        <strong><a asp-controller="UserInfo" asp-action="Index" asp-loc>Personal info</a></strong>
        <br />
        <em><a asp-controller="Tickets" asp-action="Index" asp-loc>My tickets</a></em>
        <br />
        <em><a asp-controller="Orders" asp-action="Index" asp-loc>My orders</a></em>
    </p>
</div>